services:
  - type: web
    name: panthera-site
    runtime: python
    plan: free
    buildCommand: python -m compileall backend
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
